// @flow

const FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST' = 'FETCH_DATA_REQUEST';
const FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS' = 'FETCH_DATA_SUCCESS';
const FETCH_DATA_ERROR: 'FETCH_DATA_ERROR' = 'FETCH_DATA_ERROR';
const MOVE_TO_ARCHIVE: 'MOVE_TO_ARCHIVE' = 'MOVE_TO_ARCHIVE';
const MOVE_TO_ACTUAL: 'MOVE_TO_ACTUAL' = 'MOVE_TO_ACTUAL';
const SET_META_LIST: 'SET_META_LIST' = 'SET_META_LIST';
const FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS' = 'FETCH_NEWS_SUCCESS';
const FETCH_ARCHIVE_SUCCESS: 'FETCH_ARCHIVE_SUCCESS' = 'FETCH_ARCHIVE_SUCCESS';
const UPDATE_NEWS: 'UPDATE_NEWS' = 'UPDATE_NEWS';

const DATA_EVENTS = {
	FETCH_DATA_REQUEST,
	FETCH_DATA_SUCCESS,
	FETCH_DATA_ERROR,
	MOVE_TO_ARCHIVE,
	MOVE_TO_ACTUAL,
	SET_META_LIST,
	FETCH_NEWS_SUCCESS,
	FETCH_ARCHIVE_SUCCESS,
	UPDATE_NEWS
};

export { DATA_EVENTS };
